name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
          cache: true
          
      - name: Get Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk
        
      - name: Archive Outputs
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: |
            build/app/outputs/apk/release/app-release.apk
            build/ios/archive/Runner.xcarchive

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
          cache: true
          
      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android Release Bundle
        run: flutter build appbundle --release

      - name: Archive Outputs
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app.aab
